title：你的博客    				 
SEOTitle：你的博客| 您的博客    	 
header-img：img / post-bg-rwd.jpg  	 
电子邮件：You@gmail.com	
description：“您的博客”   			
关键词：“ BY，以博客，柏荧的博客，qiubaiying，邱柏荧，iOS设备，苹果iPhone ”  
url：“ https://qiubaiying.github.io ”          
baseurl：“ ”      
sidebar：true                            
sidebar-about-description：“说点装逼的话。。。”
  