theme: jekyll-theme-leap-day
＃网站设置
title：你的博客    				  	 ＃你博客的标题
SEOTitle：你的博客| 您的博客    	  ＃显示在浏览器上搜索的时候显示的标题
header-img：img / post-bg-rwd.jpg  	 ＃显示在首页的背景图片
电子邮件：You@gmail.com	
description：“您的博客”   			 ＃网站介绍
关键词：“ BY，以博客，柏荧的博客，qiubaiying，邱柏荧，iOS设备，苹果iPhone ”  ＃关键词
url：“ https://qiubaiying.github.io ”           ＃这个就是填写你的博客地址
baseurl：“ ”       ＃这个我们不用填写
＃侧边栏设置
sidebar：true                            ＃是否开启侧边栏。
sidebar-about-description：“说点装逼的话。。。”
侧边栏-化身：/img/avatar-by.JPG       ＃你的个人头像这里你可以改成我在IMG文件夹中的两张备用照片IMG /化身米或化身克 